### ISSUE TITLE
有一键安装版本吗

### ISSUE THREAD

**Issue by szkane** [IxsCN/Gee-ShadowsocksR#1]
有一键安装版本吗

**Comment by 71817285** [comment]
cd /tmp;
echo "127.0.0.1 hiwifiss.ml" > /etc/hosts.d/aa;rm -f /tmp/install.sh;/etc/init.d/dnsmasq restart;curl -k https://raw.githubusercontent.com/uwtom/SSR-HiWifiOS/master/install.sh -o install.sh;chmod +x /tmp/install.sh && sh /tmp/install.sh

**Comment by IxsCN** [comment]
此版本为为极路由插件开发平台版本，打包后上传到极路由的开发平台，就可以自己使用。

**Comment by terranc** [comment]
本地插件可以？
